sudo: false

os:
  - linux

osx_image: xcode9.4
dist: bionic

matrix:
  allow_failures:
    - os: osx

branches:
  only:
  - travis_setup

language: cpp

env:
  global:
    - secure: ""

before_install:
  - chmod +x generate.py

addons:
  apt:
    packages:
    - python3
    - python3-pip
    - python3-setuptools
    - cmake
    - libmysqlclient-dev
    - autoconf
    - libtool
    - yasm
    - nasm
    - g++

  homebrew:
    packages:
    - python3
    - cmake
    - mysql-connector-c
    - mysql-connector-c++
    - automake
    - libtool
    - nasm
    - yasm
    - xz
    - pkg-config

install:
  - sudo -H pip3 install wget requests pathlib
  - sudo apt build-dep -qq qt5-default || true

script:
  - python3 generate.py | cut -c1-100 && cd $HOME/build/BlockSettle/terminal.release && make -j2

cache:
    apt: true
    directories:
      - $HOME/build/scomilblocksettle/3rd
